=== DanielRees604/Lab7/data/schedule.dtd
<?xml version="1.0" encoding="UTF-8">

<!-- 
	Schedule for Winter 2016 term 4 for CST
!-->

<!ELEMENT schedule (program, year, term, set, day+)>

<!-- 
	Schedule is identified by these data
!-->
<!ELEMENT program (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT term (#PCDATA)>
<!ELEMENT set (#PCDATA)>

<!--
	day constraints
-->
<!ELEMENT day (#PCDATA|period)*>
<!ATLIST day
	day_of_the_week (Monday|Tuesday|Wednesday|Thursday|Friday) #REQUIRED
>

<!--
	Period constraints
!-->
<!ELEMENT period (course, time, instructor, room, type)>

<!--
	course constraints
-->
<!ELEMENT course (name, number, id)>
<!ELEMENT name(#PCDATA)>
<!ELEMENT number(#PCDATA)>
<!ELEMENT id(#PCDATA)>


<!--
	time constraints
-->
<!ELEMENT time(start, end)>
<!ELEMENT start(#PCDATA)>
<!ELEMENT end(#PCDATA)>

<!--
	Instructor constraints
-->
<!ELEMENT instructor(first, last)>
<!ELEMENT first(#PCDATA)>
<!ELEMENT last(#PCDATA)>

<--
        type constraints
--!>

<!ELEMENT type (#PCDATA)>
<!ATLIST type
	type_of_period (Lab|Lec) #REQUIRED
>

=== DanielRees604/Lab7/data/schedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schedule SYSTEM "schedule.dtd">

<schedule>
	<program>CST</program>
	<year>2016</year>
	<term>4</term>
	<set>G</set>
	
	<day day_of_the_week = "Tuesday">
		<period>
			<course>
				<name>COMP</name>
				<number>3560</number>
				<id>345252</id>
			</course>
			<time>
				<start>11:30 AM</start>
				<end>12:20 PM</end>
			</time>
			<instructor>
				<first>Brenda</first>
				<last>Fine</last>
			</instructor>
			<room>
				<building>SW5</building>
				<room_number>1850</room_number>
			</room>
			<type type_of_period="Lec"/>
		</period>

		<period>
			<course>
				<name>COMP</name>
				<number>4711</number>
				<id>123456</id>
			</course>
			<time>
				<start>12:30 AM</start>
				<end>2:20 PM</end>
			</time>
			<instructor>
				<first>Jim</first>
				<last>Parry</last>
			</instructor>
			<room>
				<building>SE12</building>
				<room_number>320</room_number>
			</room>
			<type type_of_period="Lab"/>
		</period>
                
		<period>
			<course>
				<name>COMP</name>
				<number>4711</number>
				<id>123456</id>
			</course>
			<time>
				<start>2:30 PM</start>
				<end>3:20 PM</end>
			</time>
			<instructor>
				<first>Jim</first>
				<last>Parry</last>
			</instructor>
			<room>
				<building>SW5</building>
				<room_number>1840</room_number>
			</room>
			<type type_of_period="Lec"/>
		</period>
	</day>	
</schedule>
